-- Migration file (20250423230205_modular_platform_restructure) generated by Prisma.
-- IMPORTANT: This migration is intended for manual review and application (e.g. via pgAdmin) to avoid data loss.
-- (Below is a minimal (real) SQL migration example.)

-- (Example: add a new column (new_column) on the Subscription table.)
-- ALTER TABLE "subscriptions" ADD COLUMN "new_column" TEXT;

-- Migration: Modular Platform Restructure
-- This migration adds support for:
-- 1. Module-based access control in subscriptions
-- 2. Enterprise features (multi-location support)
-- 3. Website builder functionality
-- 4. Chain restaurant management

-- Add new fields to restaurants table for enterprise features
ALTER TABLE "restaurants" 
ADD COLUMN     "chain_name" VARCHAR(255),
ADD COLUMN     "chain_settings" JSONB,
ADD COLUMN     "custom_domain" VARCHAR(255),
ADD COLUMN     "is_chain" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "parent_restaurant_id" INTEGER,
ADD COLUMN     "website_builder_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "website_settings" JSONB;

-- Add new fields to subscriptions table for module access
ALTER TABLE "subscriptions" 
ADD COLUMN     "api_access" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "custom_domain" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "enabled_modules" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "max_customer_accounts" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "max_locations" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "max_staff_accounts" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "module_access" JSON,
ADD COLUMN     "priority_support" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "white_label" BOOLEAN NOT NULL DEFAULT false;

-- Create index for parent_restaurant_id for better query performance
CREATE INDEX "restaurants_parent_restaurant_id_idx" ON "restaurants"("parent_restaurant_id");

-- Add foreign key constraint for restaurant chains
ALTER TABLE "restaurants" 
ADD CONSTRAINT "restaurants_parent_restaurant_id_fkey" 
FOREIGN KEY ("parent_restaurant_id") 
REFERENCES "restaurants"("id") 
ON DELETE SET NULL 
ON UPDATE CASCADE;

-- (Generated SQL follows, unchanged.) 